#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx nx format:write --uncommitted
npx nx affected --target=lint --parallel --uncommitted -- --quite
npx nx affected --target=build --parallel --uncommitted
